increase default "CursorWindow.sCursorWindowSize" from 2MB to 250MB
fix error:
  java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.

caused by:
  https://github.com/aosp-mirror/platform_frameworks_base/blob/android-4.4_r1/core/res/res/values/config.xml#L942
  https://github.com/aosp-mirror/platform_frameworks_base/blob/android-9.0.0_r1/core/res/res/values/config.xml#L1902
  https://github.com/aosp-mirror/platform_frameworks_base/blob/android-13.0.0_r1/core/res/res/values/config.xml#L2249
    <!-- When a database query is executed, the results returned are paginated
         in pages of size (in KB) indicated by this value -->
    <integer name="config_cursorWindowSize">2048</integer>

triggered by:
* DB queries that return 2MB or more of data
* specifically, this occurs when the combined size of all "resource"
  external dependencies for all userscripts exceeds this threshold

underlying issue:
  https://issuetracker.google.com/issues/145977220
  https://stackoverflow.com/q/21432556
  https://stackoverflow.com/a/70684906